version: '3'

services:
  db:
    image: postgres:15.4-alpine
    container_name: kelkaj_pasvortoj_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kelkaj_pasvortoj_dev
    volumes:
      - pgdata:/var/lib/postgresql/kelkaj_pasvortoj_data
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pgdata:
